### ISSUE TITLE
Rename mp.gui.chat.safe to safeMode

### ISSUE THREAD

**Issue by Subtixx** [CocaColaBear/types-ragemp-c#26]
Wiki says its safeMode
https://wiki.rage.mp/index.php?title=Chat.safeMode

Also (client complains local is not found):
```
mp.players.local.setHealthRechargeMultiplier(0);
```
doesnt work. And this too doesnt (def not found):
```
mp.game.player.setHealthRechargeMultiplier(0.0);
```

**Comment by pixlcrashr** [comment]
@Subtixx What about that `mp.players.local.setHealthRechargeMultiplier(0);`? Is the method `setHealthRechargeMultiplier(0)` or the object space `mp.players.local` not found? Please specify.

I guess that only the method does not exist.

**Comment by ynhhoJ** [comment]
Closed
