### ISSUE TITLE
getLightsState using wrong parameters

### ISSUE THREAD

**Issue by ripkens** [CocaColaBear/types-ragemp-c#28]
https://github.com/CocaColaBear/types-ragemp-c/blob/ad7faf027cb1b92ce535ad593b517811aaf37c1e/index.d.ts#L1123

Correct code:
getLightsState(lightsOn: boolean, highbeamsOn: boolean): {
		lightsOn: number;
		highbeamsOn: number;
};

**Comment by pixlcrashr** [comment]
Was this tested ingame yet?

**Comment by ripkens** [comment]
Yes, about a year ago ..... may not be valid anymore

**Comment by pixlcrashr** [comment]
@ripkens Would you like to check it?

**Comment by ripkens** [comment]
No, i am not developing in RageMP anymore, switched to altV long time ago

**Comment by ynhhoJ** [comment]
Fixed in https://github.com/CocaColaBear/types-ragemp-c/pull/73
