### ISSUE TITLE
mp.trigger is missing

### ISSUE THREAD

**Issue by Barbarian0123** [CocaColaBear/types-ragemp-c#31]
as you can see this method right here:
[https://wiki.rage.mp/index.php?title=Trigger](https://wiki.rage.mp/index.php?title=Trigger)

**Comment by CocaColaBear** [comment]
mp.trigger is a CEF method. These types only for client-side

**Comment by jesst3r** [comment]
Greetings @CocaColaBear, unable to find mp.trigger on the clientside as well :/ maybe there are any alternative?
