### ISSUE TITLE
Missing CEF functions (like mp.trigger)

### ISSUE THREAD

**Issue by aeifr** [CocaColaBear/types-ragemp-c#40]
The mentioned function ```mp.trigger```is missing in the typescript description.

**Comment by pixlcrashr** [comment]
`mp.trigger` should not be added to this repository as it **only** exists within the browser API and, on the other, this method does not exists on the client. This may cause an unexpected behaviour on the client. Same vice versa using this API typings within browser development.

But as there was no repository available providing the browser API, I've created a repository for this single method. Take a look at it.

https://github.com/eisengrind/types-ragemp-cef

**Comment by pixlcrashr** [comment]
Is there anything left to discuss?
