### ISSUE TITLE
Update methods

### ISSUE THREAD

**Issue by time4dev** [CocaColaBear/types-ragemp-c#42]
Hello. are you going to update the files? https://rage.mp/forums/topic/6575-rage-multiplayer-10-developer-preview-1-release / if so when?

**Comment by pixlcrashr** [comment]
@time4dev Would be a good idea though, but we should push it into another branch `v1.0` e.g. .

**Comment by pixlcrashr** [comment]
Ref. #45

**Comment by pixlcrashr** [comment]
Alright. The new api methods can be added via PR to branch `v1.0`.
