### ISSUE TITLE
1.0 missed BrowserMp methods

### ISSUE THREAD

**Issue by theusersimons** [CocaColaBear/types-ragemp-c#51]
1. Browser.call(eventName, arguments...)
2. Browser.executeCached(string code)

**Comment by pixlcrashr** [comment]
Would you like to file a PR? Also: What is the changelog source for this addition?

**Comment by theusersimons** [comment]
> Would you like to file a PR? Also: What is the changelog source for this addition?

https://rage.mp/forums/topic/6575-rage-multiplayer-10-developer-preview-1-release/

Unfortunately, i can't copy the full link to the title, but try to find it by "API: CEF Updates". This should be added to the interface BrowserMp.

**Comment by pixlcrashr** [comment]
Alright then, can you file a PR? - That would relieve us of work.
