### ISSUE TITLE
Types GXT does not exists

### ISSUE THREAD

**Issue by Mauricio-Arantes** [CocaColaBear/types-ragemp-c#59]
Hello! First at all, you make a amazing job create this!!

I see in the file where you declare the interfaces you not declare the GXT functions. i made a newbie "solution" but maybe can help with something

`interface GameMp {
       ...
	zone: GameZoneMp;
	gxt: GxtTypes;

	invoke(hash: string, ...args: any[]): any;
	joaat(text: string): Hash;
	joaat(textArray: string[]): Hash[];
	wait(ms: number): void;
}`

`interface GxtTypes {
  set(labelNameOrHash:number | string, newLabelValue: string ): any;
  get(labelNameOrHash:number | string): any;
  getDefault(labelNameOrHash:number | string): any;
  reset(): any;
}
`

**Comment by CocaColaBear** [comment]
Check **v1.0** branch
